version: '2'
services:
    db:
        restart: always
        image: postgres:9.6
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=dev
            - POSTGRES_PASSWORD=dev
            - POSTGRES_DB=todo
        volumes:
            - ./data/postgres:/var/lib/postgresql/data
    nginx:
        restart: always
        build: ./nginx
        ports:
            - "80:80"
        volumes:
            - ./client/dist:/etc/nginx/html
        volumes_from:
            - web
        links:
            - web:api
    web:
        restart: always
        build: ./server
        command: bash -c "export config=/server/config.py && /usr/local/bin/gunicorn -w 2 -b :5000 wsgi:app"
        volumes:
            - ./server:/server
        expose:
            - "5000"
        depends_on:
            - db