version: '2'
services:
    db:
        restart: always
        image: postgres:9.6
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=dev
            - POSTGRES_PASSWORD=dev
            - POSTGRES_DB=todo
        volumes:
            - ./data/postgres:/var/lib/postgresql/data
    nginx:
        restart: always
        build: ./nginx/
        ports:
            - "8080:8080"
        volumes:
            - /www/static
        volumes_from:
            - web
        links:
            - web:web
    web:
        restart: always
        build: .
        command: /usr/local/bin/gunicorn -w 2 -b :5000 app:app
        # command: python app.py runserver -h 0.0.0.0 -p 5000
        volumes:
            - .:/server
        expose:
            - "5000"
        depends_on:
            - db